version: "3"

services:
  app:
    env_file:
      - ./.env
    depends_on:
      - "mongodb"
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    restart: always

  mongodb:
    image: "mongo:4.2"
    volumes:
      - ./../data:/data/db

    restart: always

